#!/usr/bin/env node
/**
 * Generate the live "is every bridge in the registry backed right now?" status
 * artifacts by running the built CLI's `solvency --all --json`:
 *
 *   - STATUS.md   — human-readable Markdown table
 *   - STATUS.json — machine-readable feed (consume it from anywhere)
 *   - badge.json  — shields.io endpoint (renders a live "bridges: N/N backed" badge)
 *
 * Run on a schedule by .github/workflows/bridge-status.yml.
 *
 *   npm run build && node scripts/gen-status.mjs
 *
 * Point <CHAIN>_RPC_URL env vars at reliable endpoints for stable numbers.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const raw = execFileSync("node", ["dist/index.js", "solvency", "--all", "--json"], {
  encoding: "utf8",
  maxBuffer: 8 * 1024 * 1024,
});
const routes = JSON.parse(raw);

const MARK = { BACKED: "✅", UNDERCOLLATERALIZED: "🔴", ERROR: "⚠️" };
const fmt = (n) => {
  const v = Number(n);
  if (!Number.isFinite(v)) return String(n);
  return v.toLocaleString("en-US", { maximumFractionDigits: 2 });
};
// Compact USD for the table — $1.18B / $45.2M / $12.3K.
const usd = (n) => {
  if (typeof n !== "number" || !Number.isFinite(n)) return "—";
  const a = Math.abs(n);
  if (a >= 1e9) return `$${(a / 1e9).toFixed(2)}B`;
  if (a >= 1e6) return `$${(a / 1e6).toFixed(1)}M`;
  if (a >= 1e3) return `$${(a / 1e3).toFixed(1)}K`;
  return `$${a.toFixed(0)}`;
};

const backed = routes.filter((r) => r.verdict === "BACKED").length;
const breached = routes.filter((r) => r.verdict === "UNDERCOLLATERALIZED").length;
const errored = routes.filter((r) => r.verdict === "ERROR").length;
const overall = breached ? "🔴 A bridge is undercollateralized" : errored ? "⚠️ Some routes could not be read" : "✅ All routes backed";

// Total value locked across every priced route — the headline dollar figure.
const totalLockedUsd = routes.reduce((s, r) => s + (typeof r.lockedUsd === "number" ? r.lockedUsd : 0), 0);
const tvlLine = totalLockedUsd > 0 ? ` Tracking **${usd(totalLockedUsd)}** of locked collateral.` : "";

const rows = routes
  .map((r) => {
    const mark = MARK[r.verdict] ?? "";
    const ratio = r.ratioPct == null ? "—" : `${r.ratioPct}%`;
    return `| ${mark} ${r.verdict} | ${r.bridge} | ${r.asset} | ${r.lockChain} → ${r.mintChain} | ${fmt(r.locked)} | ${fmt(r.minted)} | ${ratio} | ${usd(r.lockedUsd)} |`;
  })
  .join("\n");

const generatedAt = new Date().toISOString();
const now = generatedAt.replace("T", " ").slice(0, 16) + " UTC";

const md = `# Bridge backing status

${overall} — **${backed}/${routes.length} backed**${breached ? `, ${breached} breached` : ""}${errored ? `, ${errored} unreadable` : ""}.${tvlLine}

_Auto-generated by [\`evmsec solvency --all\`](https://github.com/0xSoftBoi/evmsec). Last checked: **${now}**._

Each row checks a lock-and-mint bridge invariant: the collateral **locked** in the
source-chain escrow vs the **minted** wrapped supply on the destination. A ratio
below 100% means the wrapped asset is not fully backed. **Value** is the locked
collateral priced in USD via on-chain Chainlink feeds.

| Status | Bridge | Asset | Route | Locked | Minted | Backing | Value |
| ------ | ------ | ----- | ----- | -----: | -----: | ------: | ----: |
${rows}

> ⚠️ Escrows and token mappings change. These routes were verified at registry
> seed time; re-verify against each bridge's own contracts before relying on a
> number. Not financial advice; a heuristic, not a proof.
`;

writeFileSync("STATUS.md", md);

// Machine-readable feed — same data the table is built from, plus a rollup.
const feed = {
  generatedAt,
  overall: breached ? "undercollateralized" : errored ? "degraded" : "backed",
  backed,
  breached,
  errored,
  total: routes.length,
  totalLockedUsd: totalLockedUsd > 0 ? Math.round(totalLockedUsd) : null,
  routes: routes.map((r) => ({
    id: r.id,
    bridge: r.bridge,
    asset: r.asset,
    lockChain: r.lockChain,
    mintChain: r.mintChain,
    locked: r.locked,
    minted: r.minted,
    ratioPct: r.ratioPct,
    verdict: r.verdict,
    lockedUsd: typeof r.lockedUsd === "number" ? Math.round(r.lockedUsd) : null,
    pricedVia: r.pricedVia ?? null,
  })),
};
writeFileSync("STATUS.json", JSON.stringify(feed, null, 2) + "\n");

// shields.io endpoint badge — https://shields.io/badges/endpoint-badge
const badgeColor = breached ? "red" : errored ? "orange" : "brightgreen";
const tvlSuffix = !breached && !errored && totalLockedUsd > 0 ? ` · ${usd(totalLockedUsd)}` : "";
const badge = {
  schemaVersion: 1,
  label: "bridges",
  message: `${backed}/${routes.length} backed${breached ? `, ${breached} breached` : ""}${tvlSuffix}`,
  color: badgeColor,
};
writeFileSync("badge.json", JSON.stringify(badge) + "\n");

console.error(`wrote STATUS.md, STATUS.json, badge.json — ${backed}/${routes.length} backed${breached ? `, ${breached} breached` : ""}`);
