#!/usr/bin/env node
/**
 * Generate STATUS.md — a live "is every bridge in the registry backed right now?"
 * page — by running the built CLI's `solvency --all --json` and formatting the
 * result as a Markdown table. Run on a schedule by .github/workflows/bridge-status.yml.
 *
 *   npm run build && node scripts/gen-status.mjs
 *
 * Point <CHAIN>_RPC_URL env vars at reliable endpoints for stable numbers.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const raw = execFileSync("node", ["dist/index.js", "solvency", "--all", "--json"], {
  encoding: "utf8",
  maxBuffer: 8 * 1024 * 1024,
});
const routes = JSON.parse(raw);

const MARK = { BACKED: "✅", UNDERCOLLATERALIZED: "🔴", ERROR: "⚠️" };
const fmt = (n) => {
  const v = Number(n);
  if (!Number.isFinite(v)) return String(n);
  return v.toLocaleString("en-US", { maximumFractionDigits: 2 });
};

const backed = routes.filter((r) => r.verdict === "BACKED").length;
const breached = routes.filter((r) => r.verdict === "UNDERCOLLATERALIZED").length;
const errored = routes.filter((r) => r.verdict === "ERROR").length;
const overall = breached ? "🔴 A bridge is undercollateralized" : errored ? "⚠️ Some routes could not be read" : "✅ All routes backed";

const rows = routes
  .map((r) => {
    const mark = MARK[r.verdict] ?? "";
    const ratio = r.ratioPct == null ? "—" : `${r.ratioPct}%`;
    return `| ${mark} ${r.verdict} | ${r.bridge} | ${r.asset} | ${r.lockChain} → ${r.mintChain} | ${fmt(r.locked)} | ${fmt(r.minted)} | ${ratio} |`;
  })
  .join("\n");

const now = new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC";

const md = `# Bridge backing status

${overall} — **${backed}/${routes.length} backed**${breached ? `, ${breached} breached` : ""}${errored ? `, ${errored} unreadable` : ""}.

_Auto-generated by [\`evmsec solvency --all\`](https://github.com/0xSoftBoi/evmsec). Last checked: **${now}**._

Each row checks a lock-and-mint bridge invariant: the collateral **locked** in the
source-chain escrow vs the **minted** wrapped supply on the destination. A ratio
below 100% means the wrapped asset is not fully backed.

| Status | Bridge | Asset | Route | Locked | Minted | Backing |
| ------ | ------ | ----- | ----- | -----: | -----: | ------: |
${rows}

> ⚠️ Escrows and token mappings change. These routes were verified at registry
> seed time; re-verify against each bridge's own contracts before relying on a
> number. Not financial advice; a heuristic, not a proof.
`;

writeFileSync("STATUS.md", md);
console.error(`wrote STATUS.md — ${backed}/${routes.length} backed${breached ? `, ${breached} breached` : ""}`);
